<?php
// $Id$

/**
 * @file
 * Southeast Asia Newspaper Archive Tools
 */

/**
 * computed fields handlers
 *  see https://www.drupal.org/node/126522
 *
 * Parameters:
 *
 * &$entity_field - The computed field. Used to store the computed value.
 * $entity_type - The entity type: node, user, comment, etc.
 * $entity - The actual entity (a node, user, comment, etc.)
 * $field - General field settings.
 * $instance - Field instance settings.
 * $items - The list of items.
 *
 * field_pub_title_native_translit - transliterate field_pub_title_native
 * field_pub_title_r_cul_path - make filename/url path from field_pub_title_r_cul
 * field_pub_issue_pub_path - lookup publication pathname
 *     via entity reference field_pub_issue_pub
 */

function computed_field_field_pub_title_native_translit_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $field_items = field_get_items($entity_type, $entity, 'field_pub_title_native');
  $x = array_pop($field_items);
  $native = array_pop($x);
  if (function_exists('transliteration_get')) {
    // replace untranslatable characters with underscore
    $native = transliteration_get($native, '_', language_default('language'));
    }
  $entity_field[0]['value'] = t($native);
}

function computed_field_field_pub_title_r_cul_path_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $field_items = field_get_items($entity_type, $entity, 'field_pub_title_r_cul');
  $x = array_pop($field_items);
  $newspaper = array_pop($x);
  if (function_exists('transliteration_get')) {
    $newspaper = transliteration_get($newspaper, '-', language_default('language'));
    }
  // replace blanks in path name with -
  $newspaper = strtolower(str_replace(' ', '-', $newspaper));
  $entity_field[0]['value'] = t($newspaper);
}

function computed_field_field_pub_issue_pub_path_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $field_items = field_get_items($entity_type, $entity, 'field_pub_issue_pub');
  $x = array_pop($field_items);
  $pub_nid = array_pop($x);
  $pub = node_load($pub_nid);
  $wrapper = entity_metadata_wrapper('node', $pub);
  $path = $wrapper->field_pub_title_r_cul_path->value();
  $entity_field[0]['value'] = t($path);
}

function computed_field_field_title_r_cul_translit_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $field_items = field_get_items($entity_type, $entity, 'field_title_r_cul');
  $x = array_pop($field_items);
  $newspaper = array_pop($x);
  if (function_exists('transliteration_get')) {
    $newspaper = transliteration_get($newspaper, '-', language_default('language'));
    }
  $newspaper = strtolower(str_replace(' ', '-', $newspaper));
  $entity_field[0]['value'] = t($newspaper);
}

// function computed_field_field_title_r_cul_translit_display($field, $entity_field_item, $entity_lang, $langcode, $entity) {
//   dsm(array('entity_field_item value', $entity_field_item));
//   return $entity_field_item['value'];
// }
